# Generated by Django 5.1.2 on 2024-10-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_options_votes_questions_createdat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
